#!/bin/bash
minisat instances/big/Nonogram-001-regular-table.xml output/minisatOutput/Nonogram-001.out
minisat instances/big/Nonogram-002-regular-table.xml output/minisatOutput/Nonogram-002.out
minisat instances/big/Nonogram-003-regular-table.xml output/minisatOutput/Nonogram-003.out
minisat instances/big/Nonogram-004-regular-table.xml output/minisatOutput/Nonogram-004.out
minisat instances/big/Nonogram-005-regular-table.xml output/minisatOutput/Nonogram-005.out
minisat instances/big/Nonogram-006-regular-table.xml output/minisatOutput/Nonogram-006.out
minisat instances/big/Nonogram-007-regular-table.xml output/minisatOutput/Nonogram-007.out
minisat instances/big/Nonogram-008-regular-table.xml output/minisatOutput/Nonogram-008.out
minisat instances/big/Nonogram-009-regular-table.xml output/minisatOutput/Nonogram-009.out
minisat instances/big/Nonogram-010-regular-table.xml output/minisatOutput/Nonogram-010.out
minisat instances/big/Nonogram-011-regular-table.xml output/minisatOutput/Nonogram-011.out
minisat instances/big/Nonogram-012-regular-table.xml output/minisatOutput/Nonogram-012.out
minisat instances/big/Nonogram-013-regular-table.xml output/minisatOutput/Nonogram-013.out
minisat instances/big/Nonogram-014-regular-table.xml output/minisatOutput/Nonogram-014.out
minisat instances/big/Nonogram-015-regular-table.xml output/minisatOutput/Nonogram-015.out
minisat instances/big/Nonogram-016-regular-table.xml output/minisatOutput/Nonogram-016.out
minisat instances/big/Nonogram-017-regular-table.xml output/minisatOutput/Nonogram-017.out
minisat instances/big/Nonogram-018-regular-table.xml output/minisatOutput/Nonogram-018.out
minisat instances/big/Nonogram-019-regular-table.xml output/minisatOutput/Nonogram-019.out
minisat instances/big/Nonogram-020-regular-table.xml output/minisatOutput/Nonogram-020.out
minisat instances/big/Nonogram-021-regular-table.xml output/minisatOutput/Nonogram-021.out
minisat instances/big/Nonogram-022-regular-table.xml output/minisatOutput/Nonogram-022.out
minisat instances/big/Nonogram-023-regular-table.xml output/minisatOutput/Nonogram-023.out
minisat instances/big/Nonogram-024-regular-table.xml output/minisatOutput/Nonogram-024.out
minisat instances/big/Nonogram-025-regular-table.xml output/minisatOutput/Nonogram-025.out
minisat instances/big/Nonogram-026-regular-table.xml output/minisatOutput/Nonogram-026.out
minisat instances/big/Nonogram-027-regular-table.xml output/minisatOutput/Nonogram-027.out
minisat instances/big/Nonogram-028-regular-table.xml output/minisatOutput/Nonogram-028.out
minisat instances/big/Nonogram-029-regular-table.xml output/minisatOutput/Nonogram-029.out
minisat instances/big/Nonogram-030-regular-table.xml output/minisatOutput/Nonogram-030.out
minisat instances/big/Nonogram-031-regular-table.xml output/minisatOutput/Nonogram-031.out
minisat instances/big/Nonogram-032-regular-table.xml output/minisatOutput/Nonogram-032.out
minisat instances/big/Nonogram-033-regular-table.xml output/minisatOutput/Nonogram-033.out
minisat instances/big/Nonogram-034-regular-table.xml output/minisatOutput/Nonogram-034.out
minisat instances/big/Nonogram-035-regular-table.xml output/minisatOutput/Nonogram-035.out
minisat instances/big/Nonogram-036-regular-table.xml output/minisatOutput/Nonogram-036.out
minisat instances/big/Nonogram-037-regular-table.xml output/minisatOutput/Nonogram-037.out
minisat instances/big/Nonogram-038-regular-table.xml output/minisatOutput/Nonogram-038.out
minisat instances/big/Nonogram-039-regular-table.xml output/minisatOutput/Nonogram-039.out
minisat instances/big/Nonogram-040-regular-table.xml output/minisatOutput/Nonogram-040.out
minisat instances/big/Nonogram-041-regular-table.xml output/minisatOutput/Nonogram-041.out
minisat instances/big/Nonogram-042-regular-table.xml output/minisatOutput/Nonogram-042.out
minisat instances/big/Nonogram-043-regular-table.xml output/minisatOutput/Nonogram-043.out
minisat instances/big/Nonogram-044-regular-table.xml output/minisatOutput/Nonogram-044.out
minisat instances/big/Nonogram-045-regular-table.xml output/minisatOutput/Nonogram-045.out
minisat instances/big/Nonogram-046-regular-table.xml output/minisatOutput/Nonogram-046.out
minisat instances/big/Nonogram-047-regular-table.xml output/minisatOutput/Nonogram-047.out
minisat instances/big/Nonogram-048-regular-table.xml output/minisatOutput/Nonogram-048.out
minisat instances/big/Nonogram-049-regular-table.xml output/minisatOutput/Nonogram-049.out
minisat instances/big/Nonogram-050-regular-table.xml output/minisatOutput/Nonogram-050.out
minisat instances/big/Nonogram-051-regular-table.xml output/minisatOutput/Nonogram-051.out
minisat instances/big/Nonogram-052-regular-table.xml output/minisatOutput/Nonogram-052.out
minisat instances/big/Nonogram-053-regular-table.xml output/minisatOutput/Nonogram-053.out
minisat instances/big/Nonogram-054-regular-table.xml output/minisatOutput/Nonogram-054.out
minisat instances/big/Nonogram-055-regular-table.xml output/minisatOutput/Nonogram-055.out
minisat instances/big/Nonogram-056-regular-table.xml output/minisatOutput/Nonogram-056.out
minisat instances/big/Nonogram-057-regular-table.xml output/minisatOutput/Nonogram-057.out
minisat instances/big/Nonogram-058-regular-table.xml output/minisatOutput/Nonogram-058.out
minisat instances/big/Nonogram-059-regular-table.xml output/minisatOutput/Nonogram-059.out
minisat instances/big/Nonogram-060-regular-table.xml output/minisatOutput/Nonogram-060.out
minisat instances/big/Nonogram-061-regular-table.xml output/minisatOutput/Nonogram-061.out
minisat instances/big/Nonogram-062-regular-table.xml output/minisatOutput/Nonogram-062.out
minisat instances/big/Nonogram-063-regular-table.xml output/minisatOutput/Nonogram-063.out
minisat instances/big/Nonogram-064-regular-table.xml output/minisatOutput/Nonogram-064.out
minisat instances/big/Nonogram-065-regular-table.xml output/minisatOutput/Nonogram-065.out
minisat instances/big/Nonogram-066-regular-table.xml output/minisatOutput/Nonogram-066.out
minisat instances/big/Nonogram-067-regular-table.xml output/minisatOutput/Nonogram-067.out
minisat instances/big/Nonogram-068-regular-table.xml output/minisatOutput/Nonogram-068.out
minisat instances/big/Nonogram-069-regular-table.xml output/minisatOutput/Nonogram-069.out
minisat instances/big/Nonogram-070-regular-table.xml output/minisatOutput/Nonogram-070.out
minisat instances/big/Nonogram-071-regular-table.xml output/minisatOutput/Nonogram-071.out
minisat instances/big/Nonogram-072-regular-table.xml output/minisatOutput/Nonogram-072.out
minisat instances/big/Nonogram-073-regular-table.xml output/minisatOutput/Nonogram-073.out
minisat instances/big/Nonogram-074-regular-table.xml output/minisatOutput/Nonogram-074.out
minisat instances/big/Nonogram-075-regular-table.xml output/minisatOutput/Nonogram-075.out
minisat instances/big/Nonogram-076-regular-table.xml output/minisatOutput/Nonogram-076.out
minisat instances/big/Nonogram-077-regular-table.xml output/minisatOutput/Nonogram-077.out
minisat instances/big/Nonogram-078-regular-table.xml output/minisatOutput/Nonogram-078.out
minisat instances/big/Nonogram-079-regular-table.xml output/minisatOutput/Nonogram-079.out
minisat instances/big/Nonogram-080-regular-table.xml output/minisatOutput/Nonogram-080.out
minisat instances/big/Nonogram-081-regular-table.xml output/minisatOutput/Nonogram-081.out
minisat instances/big/Nonogram-082-regular-table.xml output/minisatOutput/Nonogram-082.out
minisat instances/big/Nonogram-083-regular-table.xml output/minisatOutput/Nonogram-083.out
minisat instances/big/Nonogram-084-regular-table.xml output/minisatOutput/Nonogram-084.out
minisat instances/big/Nonogram-085-regular-table.xml output/minisatOutput/Nonogram-085.out
minisat instances/big/Nonogram-086-regular-table.xml output/minisatOutput/Nonogram-086.out
minisat instances/big/Nonogram-087-regular-table.xml output/minisatOutput/Nonogram-087.out
minisat instances/big/Nonogram-088-regular-table.xml output/minisatOutput/Nonogram-088.out
minisat instances/big/Nonogram-089-regular-table.xml output/minisatOutput/Nonogram-089.out
minisat instances/big/Nonogram-090-regular-table.xml output/minisatOutput/Nonogram-090.out
minisat instances/big/Nonogram-091-regular-table.xml output/minisatOutput/Nonogram-091.out
minisat instances/big/Nonogram-092-regular-table.xml output/minisatOutput/Nonogram-092.out
minisat instances/big/Nonogram-093-regular-table.xml output/minisatOutput/Nonogram-093.out
minisat instances/big/Nonogram-094-regular-table.xml output/minisatOutput/Nonogram-094.out
minisat instances/big/Nonogram-095-regular-table.xml output/minisatOutput/Nonogram-095.out
minisat instances/big/Nonogram-096-regular-table.xml output/minisatOutput/Nonogram-096.out
minisat instances/big/Nonogram-097-regular-table.xml output/minisatOutput/Nonogram-097.out
minisat instances/big/Nonogram-098-regular-table.xml output/minisatOutput/Nonogram-098.out
minisat instances/big/Nonogram-099-regular-table.xml output/minisatOutput/Nonogram-099.out
minisat instances/big/Nonogram-100-regular-table.xml output/minisatOutput/Nonogram-100.out
minisat instances/big/Nonogram-101-regular-table.xml output/minisatOutput/Nonogram-101.out
minisat instances/big/Nonogram-102-regular-table.xml output/minisatOutput/Nonogram-102.out
minisat instances/big/Nonogram-103-regular-table.xml output/minisatOutput/Nonogram-103.out
minisat instances/big/Nonogram-104-regular-table.xml output/minisatOutput/Nonogram-104.out
minisat instances/big/Nonogram-105-regular-table.xml output/minisatOutput/Nonogram-105.out
minisat instances/big/Nonogram-106-regular-table.xml output/minisatOutput/Nonogram-106.out
minisat instances/big/Nonogram-107-regular-table.xml output/minisatOutput/Nonogram-107.out
minisat instances/big/Nonogram-108-regular-table.xml output/minisatOutput/Nonogram-108.out
minisat instances/big/Nonogram-109-regular-table.xml output/minisatOutput/Nonogram-109.out
minisat instances/big/Nonogram-110-regular-table.xml output/minisatOutput/Nonogram-110.out
minisat instances/big/Nonogram-111-regular-table.xml output/minisatOutput/Nonogram-111.out
minisat instances/big/Nonogram-112-regular-table.xml output/minisatOutput/Nonogram-112.out
minisat instances/big/Nonogram-113-regular-table.xml output/minisatOutput/Nonogram-113.out
minisat instances/big/Nonogram-114-regular-table.xml output/minisatOutput/Nonogram-114.out
minisat instances/big/Nonogram-115-regular-table.xml output/minisatOutput/Nonogram-115.out
minisat instances/big/Nonogram-116-regular-table.xml output/minisatOutput/Nonogram-116.out
minisat instances/big/Nonogram-117-regular-table.xml output/minisatOutput/Nonogram-117.out
minisat instances/big/Nonogram-118-regular-table.xml output/minisatOutput/Nonogram-118.out
minisat instances/big/Nonogram-119-regular-table.xml output/minisatOutput/Nonogram-119.out
minisat instances/big/Nonogram-120-regular-table.xml output/minisatOutput/Nonogram-120.out
minisat instances/big/Nonogram-121-regular-table.xml output/minisatOutput/Nonogram-121.out
minisat instances/big/Nonogram-122-regular-table.xml output/minisatOutput/Nonogram-122.out
minisat instances/big/Nonogram-123-regular-table.xml output/minisatOutput/Nonogram-123.out
minisat instances/big/Nonogram-124-regular-table.xml output/minisatOutput/Nonogram-124.out
minisat instances/big/Nonogram-125-regular-table.xml output/minisatOutput/Nonogram-125.out
minisat instances/big/Nonogram-126-regular-table.xml output/minisatOutput/Nonogram-126.out
minisat instances/big/Nonogram-127-regular-table.xml output/minisatOutput/Nonogram-127.out
minisat instances/big/Nonogram-128-regular-table.xml output/minisatOutput/Nonogram-128.out
minisat instances/big/Nonogram-129-regular-table.xml output/minisatOutput/Nonogram-129.out
minisat instances/big/Nonogram-130-regular-table.xml output/minisatOutput/Nonogram-130.out
minisat instances/big/Nonogram-131-regular-table.xml output/minisatOutput/Nonogram-131.out
minisat instances/big/Nonogram-132-regular-table.xml output/minisatOutput/Nonogram-132.out
minisat instances/big/Nonogram-133-regular-table.xml output/minisatOutput/Nonogram-133.out
minisat instances/big/Nonogram-134-regular-table.xml output/minisatOutput/Nonogram-134.out
minisat instances/big/Nonogram-135-regular-table.xml output/minisatOutput/Nonogram-135.out
minisat instances/big/Nonogram-136-regular-table.xml output/minisatOutput/Nonogram-136.out
minisat instances/big/Nonogram-137-regular-table.xml output/minisatOutput/Nonogram-137.out
minisat instances/big/Nonogram-138-regular-table.xml output/minisatOutput/Nonogram-138.out
minisat instances/big/Nonogram-139-regular-table.xml output/minisatOutput/Nonogram-139.out
minisat instances/big/Nonogram-140-regular-table.xml output/minisatOutput/Nonogram-140.out
minisat instances/big/Nonogram-141-regular-table.xml output/minisatOutput/Nonogram-141.out
minisat instances/big/Nonogram-142-regular-table.xml output/minisatOutput/Nonogram-142.out
minisat instances/big/Nonogram-143-regular-table.xml output/minisatOutput/Nonogram-143.out
minisat instances/big/Nonogram-144-regular-table.xml output/minisatOutput/Nonogram-144.out
minisat instances/big/Nonogram-145-regular-table.xml output/minisatOutput/Nonogram-145.out
minisat instances/big/Nonogram-146-regular-table.xml output/minisatOutput/Nonogram-146.out
minisat instances/big/Nonogram-147-regular-table.xml output/minisatOutput/Nonogram-147.out
minisat instances/big/Nonogram-148-regular-table.xml output/minisatOutput/Nonogram-148.out
minisat instances/big/Nonogram-149-regular-table.xml output/minisatOutput/Nonogram-149.out
minisat instances/big/Nonogram-150-regular-table.xml output/minisatOutput/Nonogram-150.out
minisat instances/big/Nonogram-151-regular-table.xml output/minisatOutput/Nonogram-151.out
minisat instances/big/Nonogram-152-regular-table.xml output/minisatOutput/Nonogram-152.out
minisat instances/big/Nonogram-153-regular-table.xml output/minisatOutput/Nonogram-153.out
minisat instances/big/Nonogram-154-regular-table.xml output/minisatOutput/Nonogram-154.out
minisat instances/big/Nonogram-155-regular-table.xml output/minisatOutput/Nonogram-155.out
minisat instances/big/Nonogram-156-regular-table.xml output/minisatOutput/Nonogram-156.out
minisat instances/big/Nonogram-157-regular-table.xml output/minisatOutput/Nonogram-157.out
minisat instances/big/Nonogram-158-regular-table.xml output/minisatOutput/Nonogram-158.out
minisat instances/big/Nonogram-159-regular-table.xml output/minisatOutput/Nonogram-159.out
minisat instances/big/Nonogram-160-regular-table.xml output/minisatOutput/Nonogram-160.out
minisat instances/big/Nonogram-161-regular-table.xml output/minisatOutput/Nonogram-161.out
minisat instances/big/Nonogram-162-regular-table.xml output/minisatOutput/Nonogram-162.out
minisat instances/big/Nonogram-163-regular-table.xml output/minisatOutput/Nonogram-163.out
minisat instances/big/Nonogram-164-regular-table.xml output/minisatOutput/Nonogram-164.out
minisat instances/big/Nonogram-165-regular-table.xml output/minisatOutput/Nonogram-165.out
minisat instances/big/Nonogram-166-regular-table.xml output/minisatOutput/Nonogram-166.out
minisat instances/big/Nonogram-167-regular-table.xml output/minisatOutput/Nonogram-167.out
minisat instances/big/Nonogram-168-regular-table.xml output/minisatOutput/Nonogram-168.out
minisat instances/big/Nonogram-169-regular-table.xml output/minisatOutput/Nonogram-169.out
minisat instances/big/Nonogram-170-regular-table.xml output/minisatOutput/Nonogram-170.out
minisat instances/big/Nonogram-171-regular-table.xml output/minisatOutput/Nonogram-171.out
minisat instances/big/Nonogram-172-regular-table.xml output/minisatOutput/Nonogram-172.out
minisat instances/big/Nonogram-173-regular-table.xml output/minisatOutput/Nonogram-173.out
minisat instances/big/Nonogram-174-regular-table.xml output/minisatOutput/Nonogram-174.out
minisat instances/big/Nonogram-175-regular-table.xml output/minisatOutput/Nonogram-175.out
minisat instances/big/Nonogram-176-regular-table.xml output/minisatOutput/Nonogram-176.out
minisat instances/big/Nonogram-177-regular-table.xml output/minisatOutput/Nonogram-177.out
minisat instances/big/Nonogram-178-regular-table.xml output/minisatOutput/Nonogram-178.out
minisat instances/big/Nonogram-179-regular-table.xml output/minisatOutput/Nonogram-179.out
minisat instances/big/Nonogram-180-regular-table.xml output/minisatOutput/Nonogram-180.out
